// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Api.Data;

#nullable disable

namespace School.Api.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260819134421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("School.Api.Models.ClassRoom.ClassRoom", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClassId");

                    b.ToTable("ClassRooms");
                });

            modelBuilder.Entity("School.Api.Models.Student.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentID");

                    b.HasIndex("CID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("School.Api.Models.Student.Student", b =>
                {
                    b.HasOne("School.Api.Models.ClassRoom.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("CID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("School.Api.Models.ClassRoom.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
